// ============================================================
// Error Codes — every service error defined here
// Agents never define their own error strings
// Format: DOMAIN_SPECIFIC_ERROR
// ============================================================

export enum ErrorCode {
  // AUTH
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_EXPIRED_TOKEN = 'AUTH_EXPIRED_TOKEN',
  AUTH_MISSING_TOKEN = 'AUTH_MISSING_TOKEN',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_INSUFFICIENT_PERMISSION = 'AUTH_INSUFFICIENT_PERMISSION',
  AUTH_WORKSPACE_ACCESS_DENIED = 'AUTH_WORKSPACE_ACCESS_DENIED',

  // USER
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EMAIL_TAKEN = 'USER_EMAIL_TAKEN',
  USER_INVALID_EMAIL = 'USER_INVALID_EMAIL',

  // WORKSPACE
  WORKSPACE_NOT_FOUND = 'WORKSPACE_NOT_FOUND',
  WORKSPACE_SLUG_TAKEN = 'WORKSPACE_SLUG_TAKEN',
  WORKSPACE_MAX_MEMBERS_REACHED = 'WORKSPACE_MAX_MEMBERS_REACHED',
  WORKSPACE_MEMBER_NOT_FOUND = 'WORKSPACE_MEMBER_NOT_FOUND',
  WORKSPACE_MEMBER_ALREADY_EXISTS = 'WORKSPACE_MEMBER_ALREADY_EXISTS',
  WORKSPACE_OWNER_CANNOT_LEAVE = 'WORKSPACE_OWNER_CANNOT_LEAVE',

  // SPACE
  SPACE_NOT_FOUND = 'SPACE_NOT_FOUND',
  SPACE_ACCESS_DENIED = 'SPACE_ACCESS_DENIED',

  // LIST
  LIST_NOT_FOUND = 'LIST_NOT_FOUND',
  LIST_ARCHIVED = 'LIST_ARCHIVED',

  // TASK
  TASK_NOT_FOUND = 'TASK_NOT_FOUND',
  TASK_INVALID_PARENT = 'TASK_INVALID_PARENT',
  TASK_CIRCULAR_DEPENDENCY = 'TASK_CIRCULAR_DEPENDENCY',
  TASK_MAX_DEPTH_EXCEEDED = 'TASK_MAX_DEPTH_EXCEEDED',
  TASK_CANNOT_MOVE_TO_OWN_DESCENDANT = 'TASK_CANNOT_MOVE_TO_OWN_DESCENDANT',
  TASK_RELATION_ALREADY_EXISTS = 'TASK_RELATION_ALREADY_EXISTS',
  TASK_SELF_RELATION = 'TASK_SELF_RELATION',

  // COMMENT
  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',
  COMMENT_CANNOT_EDIT_OTHERS = 'COMMENT_CANNOT_EDIT_OTHERS',
  COMMENT_ALREADY_RESOLVED = 'COMMENT_ALREADY_RESOLVED',

  // DOC
  DOC_NOT_FOUND = 'DOC_NOT_FOUND',
  DOC_CIRCULAR_PARENT = 'DOC_CIRCULAR_PARENT',

  // CUSTOM FIELD
  CUSTOM_FIELD_NOT_FOUND = 'CUSTOM_FIELD_NOT_FOUND',
  CUSTOM_FIELD_TYPE_MISMATCH = 'CUSTOM_FIELD_TYPE_MISMATCH',
  CUSTOM_FIELD_INVALID_VALUE = 'CUSTOM_FIELD_INVALID_VALUE',

  // GOAL
  GOAL_NOT_FOUND = 'GOAL_NOT_FOUND',
  GOAL_TARGET_NOT_FOUND = 'GOAL_TARGET_NOT_FOUND',

  // TIME
  TIME_ENTRY_NOT_FOUND = 'TIME_ENTRY_NOT_FOUND',
  TIME_ENTRY_INVALID_RANGE = 'TIME_ENTRY_INVALID_RANGE',

  // FILE
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED = 'FILE_TYPE_NOT_ALLOWED',

  // AUTOMATION
  AUTOMATION_NOT_FOUND = 'AUTOMATION_NOT_FOUND',
  AUTOMATION_INVALID_CONFIG = 'AUTOMATION_INVALID_CONFIG',

  // CHECKLIST
  CHECKLIST_NOT_FOUND = 'CHECKLIST_NOT_FOUND',
  CHECKLIST_ITEM_NOT_FOUND = 'CHECKLIST_ITEM_NOT_FOUND',

  // AI
  AI_UNAVAILABLE = 'AI_UNAVAILABLE',
  AI_RATE_LIMITED = 'AI_RATE_LIMITED',
  AI_INVALID_RESPONSE = 'AI_INVALID_RESPONSE',
  AI_CONTEXT_TOO_LARGE = 'AI_CONTEXT_TOO_LARGE',
  AI_API_KEY_MISSING = 'AI_API_KEY_MISSING',
  AI_NOT_CONFIGURED = 'AI_NOT_CONFIGURED',
  AI_TIMEOUT = 'AI_TIMEOUT',
  AI_AUTH_FAILED = 'AI_AUTH_FAILED',

  // SEARCH
  SEARCH_UNAVAILABLE = 'SEARCH_UNAVAILABLE',
  SEARCH_INVALID_QUERY = 'SEARCH_INVALID_QUERY',

  // VALIDATION
  VALIDATION_INVALID_INPUT = 'VALIDATION_INVALID_INPUT',
  VALIDATION_MISSING_FIELD = 'VALIDATION_MISSING_FIELD',
  VALIDATION_INVALID_UUID = 'VALIDATION_INVALID_UUID',
  VALIDATION_INVALID_DATE = 'VALIDATION_INVALID_DATE',
  VALIDATION_STRING_TOO_LONG = 'VALIDATION_STRING_TOO_LONG',
  VALIDATION_STRING_TOO_SHORT = 'VALIDATION_STRING_TOO_SHORT',

  // SYSTEM
  SYSTEM_INTERNAL_ERROR = 'SYSTEM_INTERNAL_ERROR',
  SYSTEM_SERVICE_UNAVAILABLE = 'SYSTEM_SERVICE_UNAVAILABLE',
  SYSTEM_NOT_IMPLEMENTED = 'SYSTEM_NOT_IMPLEMENTED',
  SYSTEM_RATE_LIMITED = 'SYSTEM_RATE_LIMITED',
}

// ============================================================
// Error response envelope — the ONLY error shape in the system
// ============================================================

export interface AppErrorResponse {
  error: {
    code: ErrorCode
    message: string
    status: number
    traceId: string
    details?: Record<string, unknown>
  }
}

// Map error codes to HTTP status codes
export const ERROR_STATUS_MAP: Record<ErrorCode, number> = {
  [ErrorCode.AUTH_INVALID_TOKEN]: 401,
  [ErrorCode.AUTH_EXPIRED_TOKEN]: 401,
  [ErrorCode.AUTH_MISSING_TOKEN]: 401,
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 401,
  [ErrorCode.AUTH_INSUFFICIENT_PERMISSION]: 403,
  [ErrorCode.AUTH_WORKSPACE_ACCESS_DENIED]: 403,

  [ErrorCode.USER_NOT_FOUND]: 404,
  [ErrorCode.USER_EMAIL_TAKEN]: 409,
  [ErrorCode.USER_INVALID_EMAIL]: 422,

  [ErrorCode.WORKSPACE_NOT_FOUND]: 404,
  [ErrorCode.WORKSPACE_SLUG_TAKEN]: 409,
  [ErrorCode.WORKSPACE_MAX_MEMBERS_REACHED]: 422,
  [ErrorCode.WORKSPACE_MEMBER_NOT_FOUND]: 404,
  [ErrorCode.WORKSPACE_MEMBER_ALREADY_EXISTS]: 409,
  [ErrorCode.WORKSPACE_OWNER_CANNOT_LEAVE]: 422,

  [ErrorCode.SPACE_NOT_FOUND]: 404,
  [ErrorCode.SPACE_ACCESS_DENIED]: 403,

  [ErrorCode.LIST_NOT_FOUND]: 404,
  [ErrorCode.LIST_ARCHIVED]: 422,

  [ErrorCode.TASK_NOT_FOUND]: 404,
  [ErrorCode.TASK_INVALID_PARENT]: 422,
  [ErrorCode.TASK_CIRCULAR_DEPENDENCY]: 422,
  [ErrorCode.TASK_MAX_DEPTH_EXCEEDED]: 422,
  [ErrorCode.TASK_CANNOT_MOVE_TO_OWN_DESCENDANT]: 422,
  [ErrorCode.TASK_RELATION_ALREADY_EXISTS]: 409,
  [ErrorCode.TASK_SELF_RELATION]: 422,

  [ErrorCode.COMMENT_NOT_FOUND]: 404,
  [ErrorCode.COMMENT_CANNOT_EDIT_OTHERS]: 403,
  [ErrorCode.COMMENT_ALREADY_RESOLVED]: 422,

  [ErrorCode.DOC_NOT_FOUND]: 404,
  [ErrorCode.DOC_CIRCULAR_PARENT]: 422,

  [ErrorCode.CUSTOM_FIELD_NOT_FOUND]: 404,
  [ErrorCode.CUSTOM_FIELD_TYPE_MISMATCH]: 422,
  [ErrorCode.CUSTOM_FIELD_INVALID_VALUE]: 422,

  [ErrorCode.GOAL_NOT_FOUND]: 404,
  [ErrorCode.GOAL_TARGET_NOT_FOUND]: 404,

  [ErrorCode.TIME_ENTRY_NOT_FOUND]: 404,
  [ErrorCode.TIME_ENTRY_INVALID_RANGE]: 422,

  [ErrorCode.FILE_NOT_FOUND]: 404,
  [ErrorCode.FILE_TOO_LARGE]: 422,
  [ErrorCode.FILE_TYPE_NOT_ALLOWED]: 422,

  [ErrorCode.AUTOMATION_NOT_FOUND]: 404,
  [ErrorCode.AUTOMATION_INVALID_CONFIG]: 422,

  [ErrorCode.CHECKLIST_NOT_FOUND]: 404,
  [ErrorCode.CHECKLIST_ITEM_NOT_FOUND]: 404,

  [ErrorCode.AI_UNAVAILABLE]: 503,
  [ErrorCode.AI_RATE_LIMITED]: 429,
  [ErrorCode.AI_INVALID_RESPONSE]: 500,
  [ErrorCode.AI_CONTEXT_TOO_LARGE]: 422,
  [ErrorCode.AI_API_KEY_MISSING]: 503,
  [ErrorCode.AI_NOT_CONFIGURED]: 422,
  [ErrorCode.AI_TIMEOUT]: 504,
  [ErrorCode.AI_AUTH_FAILED]: 401,

  [ErrorCode.SEARCH_UNAVAILABLE]: 503,
  [ErrorCode.SEARCH_INVALID_QUERY]: 422,

  [ErrorCode.VALIDATION_INVALID_INPUT]: 422,
  [ErrorCode.VALIDATION_MISSING_FIELD]: 422,
  [ErrorCode.VALIDATION_INVALID_UUID]: 422,
  [ErrorCode.VALIDATION_INVALID_DATE]: 422,
  [ErrorCode.VALIDATION_STRING_TOO_LONG]: 422,
  [ErrorCode.VALIDATION_STRING_TOO_SHORT]: 422,

  [ErrorCode.SYSTEM_INTERNAL_ERROR]: 500,
  [ErrorCode.SYSTEM_SERVICE_UNAVAILABLE]: 503,
  [ErrorCode.SYSTEM_NOT_IMPLEMENTED]: 501,
  [ErrorCode.SYSTEM_RATE_LIMITED]: 429,
}
