// ============================================================
// Error Codes — every service error defined here
// Agents never define their own error strings
// Format: DOMAIN_SPECIFIC_ERROR
// ============================================================

export enum ErrorCode {
  // AUTH
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_EXPIRED_TOKEN = 'AUTH_EXPIRED_TOKEN',
  AUTH_MISSING_TOKEN = 'AUTH_MISSING_TOKEN',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_INSUFFICIENT_PERMISSION = 'AUTH_INSUFFICIENT_PERMISSION',
  AUTH_WORKSPACE_ACCESS_DENIED = 'AUTH_WORKSPACE_ACCESS_DENIED',
  AUTH_RESET_TOKEN_INVALID = 'AUTH_RESET_TOKEN_INVALID',
  AUTH_RESET_TOKEN_EXPIRED = 'AUTH_RESET_TOKEN_EXPIRED',
  AUTH_VERIFY_TOKEN_INVALID = 'AUTH_VERIFY_TOKEN_INVALID',

  // USER
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EMAIL_TAKEN = 'USER_EMAIL_TAKEN',
  USER_INVALID_EMAIL = 'USER_INVALID_EMAIL',
  USER_EMAIL_NOT_FOUND = 'USER_EMAIL_NOT_FOUND',
  USER_TOKEN_INVALID = 'USER_TOKEN_INVALID',
  USER_TOKEN_EXPIRED = 'USER_TOKEN_EXPIRED',
  USER_TOKEN_ALREADY_USED = 'USER_TOKEN_ALREADY_USED',
  USER_EMAIL_ALREADY_VERIFIED = 'USER_EMAIL_ALREADY_VERIFIED',

  // WORKSPACE
  WORKSPACE_NOT_FOUND = 'WORKSPACE_NOT_FOUND',
  WORKSPACE_SLUG_TAKEN = 'WORKSPACE_SLUG_TAKEN',
  WORKSPACE_MAX_MEMBERS_REACHED = 'WORKSPACE_MAX_MEMBERS_REACHED',
  WORKSPACE_MEMBER_NOT_FOUND = 'WORKSPACE_MEMBER_NOT_FOUND',
  WORKSPACE_MEMBER_ALREADY_EXISTS = 'WORKSPACE_MEMBER_ALREADY_EXISTS',
  WORKSPACE_OWNER_CANNOT_LEAVE = 'WORKSPACE_OWNER_CANNOT_LEAVE',

  // SPACE
  SPACE_NOT_FOUND = 'SPACE_NOT_FOUND',
  SPACE_ACCESS_DENIED = 'SPACE_ACCESS_DENIED',

  // LIST
  LIST_NOT_FOUND = 'LIST_NOT_FOUND',
  LIST_ARCHIVED = 'LIST_ARCHIVED',

  // LIST STATUS
  LIST_STATUS_NOT_FOUND = 'LIST_STATUS_NOT_FOUND',
  LIST_STATUS_ALREADY_EXISTS = 'LIST_STATUS_ALREADY_EXISTS',

  // FOLDER
  FOLDER_NOT_FOUND = 'FOLDER_NOT_FOUND',

  // TASK
  TASK_NOT_FOUND = 'TASK_NOT_FOUND',
  TASK_INVALID_PARENT = 'TASK_INVALID_PARENT',
  TASK_CIRCULAR_DEPENDENCY = 'TASK_CIRCULAR_DEPENDENCY',
  TASK_MAX_DEPTH_EXCEEDED = 'TASK_MAX_DEPTH_EXCEEDED',
  TASK_CANNOT_MOVE_TO_OWN_DESCENDANT = 'TASK_CANNOT_MOVE_TO_OWN_DESCENDANT',
  TASK_RELATION_ALREADY_EXISTS = 'TASK_RELATION_ALREADY_EXISTS',
  TASK_SELF_RELATION = 'TASK_SELF_RELATION',

  // TASK TEMPLATE
  TASK_TEMPLATE_NOT_FOUND = 'TASK_TEMPLATE_NOT_FOUND',

  // TASK FORM
  TASK_FORM_NOT_FOUND = 'TASK_FORM_NOT_FOUND',
  TASK_FORM_INACTIVE = 'TASK_FORM_INACTIVE',
  TASK_FORM_SLUG_TAKEN = 'TASK_FORM_SLUG_TAKEN',

  // RECURRING
  RECURRING_CONFIG_NOT_FOUND = 'RECURRING_CONFIG_NOT_FOUND',

  // SPRINT
  SPRINT_NOT_FOUND = 'SPRINT_NOT_FOUND',
  SPRINT_ALREADY_ACTIVE = 'SPRINT_ALREADY_ACTIVE',
  SPRINT_NOT_ACTIVE = 'SPRINT_NOT_ACTIVE',

  // COMMENT
  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',
  COMMENT_CANNOT_EDIT_OTHERS = 'COMMENT_CANNOT_EDIT_OTHERS',
  COMMENT_ALREADY_RESOLVED = 'COMMENT_ALREADY_RESOLVED',

  // DOC
  DOC_NOT_FOUND = 'DOC_NOT_FOUND',
  DOC_CIRCULAR_PARENT = 'DOC_CIRCULAR_PARENT',
  DOC_ACCESS_DENIED = 'DOC_ACCESS_DENIED',
  DOC_PERMISSION_NOT_FOUND = 'DOC_PERMISSION_NOT_FOUND',
  DOC_VERSION_NOT_FOUND = 'DOC_VERSION_NOT_FOUND',
  DOC_SHARE_LINK_EXPIRED = 'DOC_SHARE_LINK_EXPIRED',
  DOC_SHARE_LINK_NOT_FOUND = 'DOC_SHARE_LINK_NOT_FOUND',
  DOC_SHARE_NOT_FOUND = 'DOC_SHARE_NOT_FOUND',

  // CUSTOM FIELD
  CUSTOM_FIELD_NOT_FOUND = 'CUSTOM_FIELD_NOT_FOUND',
  CUSTOM_FIELD_TYPE_MISMATCH = 'CUSTOM_FIELD_TYPE_MISMATCH',
  CUSTOM_FIELD_INVALID_VALUE = 'CUSTOM_FIELD_INVALID_VALUE',

  // GOAL
  GOAL_NOT_FOUND = 'GOAL_NOT_FOUND',
  GOAL_TARGET_NOT_FOUND = 'GOAL_TARGET_NOT_FOUND',
  GOAL_FOLDER_NOT_FOUND = 'GOAL_FOLDER_NOT_FOUND',
  GOAL_FOLDER_NAME_TAKEN = 'GOAL_FOLDER_NAME_TAKEN',

  // DASHBOARD
  DASHBOARD_NOT_FOUND = 'DASHBOARD_NOT_FOUND',
  DASHBOARD_ACCESS_DENIED = 'DASHBOARD_ACCESS_DENIED',
  WIDGET_NOT_FOUND = 'WIDGET_NOT_FOUND',

  // VIEW
  VIEW_NOT_FOUND = 'VIEW_NOT_FOUND',
  VIEW_ACCESS_DENIED = 'VIEW_ACCESS_DENIED',

  // TIME
  TIME_ENTRY_NOT_FOUND = 'TIME_ENTRY_NOT_FOUND',
  TIME_ENTRY_INVALID_RANGE = 'TIME_ENTRY_INVALID_RANGE',

  // FILE
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED = 'FILE_TYPE_NOT_ALLOWED',

  // AUTOMATION
  AUTOMATION_NOT_FOUND = 'AUTOMATION_NOT_FOUND',
  AUTOMATION_INVALID_CONFIG = 'AUTOMATION_INVALID_CONFIG',

  // WEBHOOK
  WEBHOOK_NOT_FOUND = 'WEBHOOK_NOT_FOUND',

  // CHECKLIST
  CHECKLIST_NOT_FOUND = 'CHECKLIST_NOT_FOUND',
  CHECKLIST_ITEM_NOT_FOUND = 'CHECKLIST_ITEM_NOT_FOUND',

  // API KEYS
  API_KEY_NOT_FOUND = 'API_KEY_NOT_FOUND',
  API_KEY_INVALID = 'API_KEY_INVALID',
  API_KEY_EXPIRED = 'API_KEY_EXPIRED',
  API_KEY_SCOPE_DENIED = 'API_KEY_SCOPE_DENIED',

  // SAVED SEARCH
  SAVED_SEARCH_NOT_FOUND = 'SAVED_SEARCH_NOT_FOUND',

  // FAVORITES
  FAVORITE_NOT_FOUND = 'FAVORITE_NOT_FOUND',
  FAVORITE_ALREADY_EXISTS = 'FAVORITE_ALREADY_EXISTS',

  // TEAMS
  TEAM_NOT_FOUND = 'TEAM_NOT_FOUND',
  TEAM_MEMBER_ALREADY_EXISTS = 'TEAM_MEMBER_ALREADY_EXISTS',
  TEAM_MEMBER_NOT_FOUND = 'TEAM_MEMBER_NOT_FOUND',

  // TRASH
  TRASH_ITEM_NOT_FOUND = 'TRASH_ITEM_NOT_FOUND',

  // SIDEBAR
  SIDEBAR_CONFIG_NOT_FOUND = 'SIDEBAR_CONFIG_NOT_FOUND',

  // PREFERENCES
  PREFERENCES_NOT_FOUND = 'PREFERENCES_NOT_FOUND',

  // TASK SHARE LINK
  TASK_SHARE_LINK_NOT_FOUND = 'TASK_SHARE_LINK_NOT_FOUND',
  TASK_SHARE_LINK_EXPIRED = 'TASK_SHARE_LINK_EXPIRED',
  TASK_SHARE_LINK_INACTIVE = 'TASK_SHARE_LINK_INACTIVE',

  // TASK TYPE
  TASK_TYPE_NOT_FOUND = 'TASK_TYPE_NOT_FOUND',
  TASK_TYPE_ALREADY_EXISTS = 'TASK_TYPE_ALREADY_EXISTS',

  // WORKSPACE INVITE
  WORKSPACE_INVITE_NOT_FOUND = 'WORKSPACE_INVITE_NOT_FOUND',
  WORKSPACE_INVITE_EXPIRED = 'WORKSPACE_INVITE_EXPIRED',
  WORKSPACE_INVITE_ALREADY_ACCEPTED = 'WORKSPACE_INVITE_ALREADY_ACCEPTED',

  // COMMENT ASSIGNMENT
  COMMENT_ASSIGNMENT_NOT_FOUND = 'COMMENT_ASSIGNMENT_NOT_FOUND',
  COMMENT_ALREADY_ASSIGNED = 'COMMENT_ALREADY_ASSIGNED',

  // CHAT
  CHANNEL_NOT_FOUND = 'CHANNEL_NOT_FOUND',
  CHANNEL_ACCESS_DENIED = 'CHANNEL_ACCESS_DENIED',
  CHANNEL_ALREADY_MEMBER = 'CHANNEL_ALREADY_MEMBER',
  CHANNEL_NOT_MEMBER = 'CHANNEL_NOT_MEMBER',
  CHANNEL_CANNOT_LEAVE_DM = 'CHANNEL_CANNOT_LEAVE_DM',
  MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND',
  MESSAGE_CANNOT_EDIT_OTHERS = 'MESSAGE_CANNOT_EDIT_OTHERS',
  DM_CHANNEL_ALREADY_EXISTS = 'DM_CHANNEL_ALREADY_EXISTS',

  // NOTIFICATION (extended)
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_ALREADY_CLEARED = 'NOTIFICATION_ALREADY_CLEARED',

  // REMINDER
  REMINDER_NOT_FOUND = 'REMINDER_NOT_FOUND',

  // FORM
  FORM_NOT_FOUND = 'FORM_NOT_FOUND',
  FORM_INACTIVE = 'FORM_INACTIVE',

  // AUDIT
  AUDIT_LOG_NOT_FOUND = 'AUDIT_LOG_NOT_FOUND',

  // DASHBOARD TEMPLATE
  DASHBOARD_TEMPLATE_NOT_FOUND = 'DASHBOARD_TEMPLATE_NOT_FOUND',

  // TEMPLATE
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',

  // FIELD PERMISSION
  FIELD_PERMISSION_NOT_FOUND = 'FIELD_PERMISSION_NOT_FOUND',

  // AI
  AI_UNAVAILABLE = 'AI_UNAVAILABLE',
  AI_RATE_LIMITED = 'AI_RATE_LIMITED',
  AI_INVALID_RESPONSE = 'AI_INVALID_RESPONSE',
  AI_CONTEXT_TOO_LARGE = 'AI_CONTEXT_TOO_LARGE',
  AI_API_KEY_MISSING = 'AI_API_KEY_MISSING',

  // SEARCH
  SEARCH_UNAVAILABLE = 'SEARCH_UNAVAILABLE',
  SEARCH_INVALID_QUERY = 'SEARCH_INVALID_QUERY',

  // VALIDATION
  VALIDATION_INVALID_INPUT = 'VALIDATION_INVALID_INPUT',
  VALIDATION_MISSING_FIELD = 'VALIDATION_MISSING_FIELD',
  VALIDATION_INVALID_UUID = 'VALIDATION_INVALID_UUID',
  VALIDATION_INVALID_DATE = 'VALIDATION_INVALID_DATE',
  VALIDATION_STRING_TOO_LONG = 'VALIDATION_STRING_TOO_LONG',
  VALIDATION_STRING_TOO_SHORT = 'VALIDATION_STRING_TOO_SHORT',

  // SYSTEM
  SYSTEM_INTERNAL_ERROR = 'SYSTEM_INTERNAL_ERROR',
  SYSTEM_SERVICE_UNAVAILABLE = 'SYSTEM_SERVICE_UNAVAILABLE',
  SYSTEM_NOT_IMPLEMENTED = 'SYSTEM_NOT_IMPLEMENTED',
  SYSTEM_RATE_LIMITED = 'SYSTEM_RATE_LIMITED',
}

// ============================================================
// Error response envelope — the ONLY error shape in the system
// ============================================================

export interface AppErrorResponse {
  error: {
    code: ErrorCode
    message: string
    status: number
    traceId: string
    details?: Record<string, unknown>
  }
}

// Map error codes to HTTP status codes
export const ERROR_STATUS_MAP: Record<ErrorCode, number> = {
  [ErrorCode.AUTH_INVALID_TOKEN]: 401,
  [ErrorCode.AUTH_EXPIRED_TOKEN]: 401,
  [ErrorCode.AUTH_MISSING_TOKEN]: 401,
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 401,
  [ErrorCode.AUTH_INSUFFICIENT_PERMISSION]: 403,
  [ErrorCode.AUTH_WORKSPACE_ACCESS_DENIED]: 403,
  [ErrorCode.AUTH_RESET_TOKEN_INVALID]: 400,
  [ErrorCode.AUTH_RESET_TOKEN_EXPIRED]: 400,
  [ErrorCode.AUTH_VERIFY_TOKEN_INVALID]: 400,

  [ErrorCode.USER_NOT_FOUND]: 404,
  [ErrorCode.USER_EMAIL_TAKEN]: 409,
  [ErrorCode.USER_INVALID_EMAIL]: 422,
  [ErrorCode.USER_EMAIL_NOT_FOUND]: 404,
  [ErrorCode.USER_TOKEN_INVALID]: 400,
  [ErrorCode.USER_TOKEN_EXPIRED]: 400,
  [ErrorCode.USER_TOKEN_ALREADY_USED]: 400,
  [ErrorCode.USER_EMAIL_ALREADY_VERIFIED]: 409,

  [ErrorCode.WORKSPACE_NOT_FOUND]: 404,
  [ErrorCode.WORKSPACE_SLUG_TAKEN]: 409,
  [ErrorCode.WORKSPACE_MAX_MEMBERS_REACHED]: 422,
  [ErrorCode.WORKSPACE_MEMBER_NOT_FOUND]: 404,
  [ErrorCode.WORKSPACE_MEMBER_ALREADY_EXISTS]: 409,
  [ErrorCode.WORKSPACE_OWNER_CANNOT_LEAVE]: 422,

  [ErrorCode.SPACE_NOT_FOUND]: 404,
  [ErrorCode.SPACE_ACCESS_DENIED]: 403,

  [ErrorCode.LIST_NOT_FOUND]: 404,
  [ErrorCode.LIST_ARCHIVED]: 422,

  [ErrorCode.LIST_STATUS_NOT_FOUND]: 404,
  [ErrorCode.LIST_STATUS_ALREADY_EXISTS]: 409,

  [ErrorCode.FOLDER_NOT_FOUND]: 404,

  [ErrorCode.TASK_NOT_FOUND]: 404,
  [ErrorCode.TASK_INVALID_PARENT]: 422,
  [ErrorCode.TASK_CIRCULAR_DEPENDENCY]: 422,
  [ErrorCode.TASK_MAX_DEPTH_EXCEEDED]: 422,
  [ErrorCode.TASK_CANNOT_MOVE_TO_OWN_DESCENDANT]: 422,
  [ErrorCode.TASK_RELATION_ALREADY_EXISTS]: 409,
  [ErrorCode.TASK_SELF_RELATION]: 422,

  [ErrorCode.TASK_TEMPLATE_NOT_FOUND]: 404,

  [ErrorCode.TASK_FORM_NOT_FOUND]: 404,
  [ErrorCode.TASK_FORM_INACTIVE]: 422,
  [ErrorCode.TASK_FORM_SLUG_TAKEN]: 409,

  [ErrorCode.RECURRING_CONFIG_NOT_FOUND]: 404,

  [ErrorCode.SPRINT_NOT_FOUND]: 404,
  [ErrorCode.SPRINT_ALREADY_ACTIVE]: 409,
  [ErrorCode.SPRINT_NOT_ACTIVE]: 409,

  [ErrorCode.COMMENT_NOT_FOUND]: 404,
  [ErrorCode.COMMENT_CANNOT_EDIT_OTHERS]: 403,
  [ErrorCode.COMMENT_ALREADY_RESOLVED]: 422,

  [ErrorCode.DOC_NOT_FOUND]: 404,
  [ErrorCode.DOC_CIRCULAR_PARENT]: 422,
  [ErrorCode.DOC_ACCESS_DENIED]: 403,
  [ErrorCode.DOC_PERMISSION_NOT_FOUND]: 404,
  [ErrorCode.DOC_VERSION_NOT_FOUND]: 404,
  [ErrorCode.DOC_SHARE_LINK_EXPIRED]: 410,
  [ErrorCode.DOC_SHARE_LINK_NOT_FOUND]: 404,
  [ErrorCode.DOC_SHARE_NOT_FOUND]: 404,

  [ErrorCode.CUSTOM_FIELD_NOT_FOUND]: 404,
  [ErrorCode.CUSTOM_FIELD_TYPE_MISMATCH]: 422,
  [ErrorCode.CUSTOM_FIELD_INVALID_VALUE]: 422,

  [ErrorCode.GOAL_NOT_FOUND]: 404,
  [ErrorCode.GOAL_TARGET_NOT_FOUND]: 404,
  [ErrorCode.GOAL_FOLDER_NOT_FOUND]: 404,
  [ErrorCode.GOAL_FOLDER_NAME_TAKEN]: 409,

  [ErrorCode.DASHBOARD_NOT_FOUND]: 404,
  [ErrorCode.DASHBOARD_ACCESS_DENIED]: 403,
  [ErrorCode.WIDGET_NOT_FOUND]: 404,

  [ErrorCode.VIEW_NOT_FOUND]: 404,
  [ErrorCode.VIEW_ACCESS_DENIED]: 403,

  [ErrorCode.TIME_ENTRY_NOT_FOUND]: 404,
  [ErrorCode.TIME_ENTRY_INVALID_RANGE]: 422,

  [ErrorCode.FILE_NOT_FOUND]: 404,
  [ErrorCode.FILE_TOO_LARGE]: 422,
  [ErrorCode.FILE_TYPE_NOT_ALLOWED]: 422,

  [ErrorCode.AUTOMATION_NOT_FOUND]: 404,
  [ErrorCode.AUTOMATION_INVALID_CONFIG]: 422,

  [ErrorCode.WEBHOOK_NOT_FOUND]: 404,

  [ErrorCode.CHECKLIST_NOT_FOUND]: 404,
  [ErrorCode.CHECKLIST_ITEM_NOT_FOUND]: 404,

  [ErrorCode.API_KEY_NOT_FOUND]: 404,
  [ErrorCode.API_KEY_INVALID]: 401,
  [ErrorCode.API_KEY_EXPIRED]: 401,
  [ErrorCode.API_KEY_SCOPE_DENIED]: 403,

  [ErrorCode.SAVED_SEARCH_NOT_FOUND]: 404,

  [ErrorCode.FAVORITE_NOT_FOUND]: 404,
  [ErrorCode.FAVORITE_ALREADY_EXISTS]: 409,

  [ErrorCode.TEAM_NOT_FOUND]: 404,
  [ErrorCode.TEAM_MEMBER_ALREADY_EXISTS]: 409,
  [ErrorCode.TEAM_MEMBER_NOT_FOUND]: 404,

  [ErrorCode.TRASH_ITEM_NOT_FOUND]: 404,

  [ErrorCode.SIDEBAR_CONFIG_NOT_FOUND]: 404,

  [ErrorCode.PREFERENCES_NOT_FOUND]: 404,

  [ErrorCode.TASK_SHARE_LINK_NOT_FOUND]: 404,
  [ErrorCode.TASK_SHARE_LINK_EXPIRED]: 410,
  [ErrorCode.TASK_SHARE_LINK_INACTIVE]: 422,

  [ErrorCode.TASK_TYPE_NOT_FOUND]: 404,
  [ErrorCode.TASK_TYPE_ALREADY_EXISTS]: 409,

  [ErrorCode.WORKSPACE_INVITE_NOT_FOUND]: 404,
  [ErrorCode.WORKSPACE_INVITE_EXPIRED]: 410,
  [ErrorCode.WORKSPACE_INVITE_ALREADY_ACCEPTED]: 409,

  [ErrorCode.COMMENT_ASSIGNMENT_NOT_FOUND]: 404,
  [ErrorCode.COMMENT_ALREADY_ASSIGNED]: 409,

  [ErrorCode.CHANNEL_NOT_FOUND]: 404,
  [ErrorCode.CHANNEL_ACCESS_DENIED]: 403,
  [ErrorCode.CHANNEL_ALREADY_MEMBER]: 409,
  [ErrorCode.CHANNEL_NOT_MEMBER]: 422,
  [ErrorCode.CHANNEL_CANNOT_LEAVE_DM]: 422,
  [ErrorCode.MESSAGE_NOT_FOUND]: 404,
  [ErrorCode.MESSAGE_CANNOT_EDIT_OTHERS]: 403,
  [ErrorCode.DM_CHANNEL_ALREADY_EXISTS]: 409,

  [ErrorCode.NOTIFICATION_NOT_FOUND]: 404,
  [ErrorCode.NOTIFICATION_ALREADY_CLEARED]: 422,

  [ErrorCode.REMINDER_NOT_FOUND]: 404,

  [ErrorCode.FORM_NOT_FOUND]: 404,
  [ErrorCode.FORM_INACTIVE]: 422,

  [ErrorCode.AUDIT_LOG_NOT_FOUND]: 404,

  [ErrorCode.DASHBOARD_TEMPLATE_NOT_FOUND]: 404,

  [ErrorCode.TEMPLATE_NOT_FOUND]: 404,

  [ErrorCode.FIELD_PERMISSION_NOT_FOUND]: 404,

  [ErrorCode.AI_UNAVAILABLE]: 503,
  [ErrorCode.AI_RATE_LIMITED]: 429,
  [ErrorCode.AI_INVALID_RESPONSE]: 502,
  [ErrorCode.AI_CONTEXT_TOO_LARGE]: 422,
  [ErrorCode.AI_API_KEY_MISSING]: 503,

  [ErrorCode.SEARCH_UNAVAILABLE]: 503,
  [ErrorCode.SEARCH_INVALID_QUERY]: 422,

  [ErrorCode.VALIDATION_INVALID_INPUT]: 422,
  [ErrorCode.VALIDATION_MISSING_FIELD]: 422,
  [ErrorCode.VALIDATION_INVALID_UUID]: 422,
  [ErrorCode.VALIDATION_INVALID_DATE]: 422,
  [ErrorCode.VALIDATION_STRING_TOO_LONG]: 422,
  [ErrorCode.VALIDATION_STRING_TOO_SHORT]: 422,

  [ErrorCode.SYSTEM_INTERNAL_ERROR]: 500,
  [ErrorCode.SYSTEM_SERVICE_UNAVAILABLE]: 503,
  [ErrorCode.SYSTEM_NOT_IMPLEMENTED]: 501,
  [ErrorCode.SYSTEM_RATE_LIMITED]: 429,
}
