-- Migration 014: Change users.id and workspaces.id from UUID to TEXT
-- Reason: Clerk user IDs are string-format (user_xxx) not UUIDs.
-- DB was empty when applied so no data migration needed.

BEGIN;

-- ── Step 1: Drop all FK constraints referencing users(id) or workspaces(id) ───

ALTER TABLE api_keys DROP CONSTRAINT api_keys_workspace_id_fkey;
ALTER TABLE api_keys DROP CONSTRAINT api_keys_user_id_fkey;
ALTER TABLE audit_logs DROP CONSTRAINT audit_logs_workspace_id_fkey;
ALTER TABLE audit_logs DROP CONSTRAINT audit_logs_actor_id_fkey;
ALTER TABLE automation_runs DROP CONSTRAINT automation_runs_workspace_id_fkey;
ALTER TABLE automations DROP CONSTRAINT automations_created_by_fkey;
ALTER TABLE automations DROP CONSTRAINT automations_workspace_id_fkey;
ALTER TABLE channel_members DROP CONSTRAINT channel_members_user_id_fkey;
ALTER TABLE channels DROP CONSTRAINT channels_workspace_id_fkey;
ALTER TABLE channels DROP CONSTRAINT channels_created_by_fkey;
ALTER TABLE chat_mentions DROP CONSTRAINT chat_mentions_user_id_fkey;
ALTER TABLE chat_messages DROP CONSTRAINT chat_messages_sender_id_fkey;
ALTER TABLE checklist_items DROP CONSTRAINT checklist_items_assignee_id_fkey;
ALTER TABLE comment_assignments DROP CONSTRAINT comment_assignments_assigned_by_fkey;
ALTER TABLE comment_assignments DROP CONSTRAINT comment_assignments_assignee_id_fkey;
ALTER TABLE comment_reactions DROP CONSTRAINT comment_reactions_user_id_fkey;
ALTER TABLE comments DROP CONSTRAINT comments_user_id_fkey;
ALTER TABLE custom_fields DROP CONSTRAINT custom_fields_workspace_id_fkey;
ALTER TABLE dashboards DROP CONSTRAINT dashboards_owner_id_fkey;
ALTER TABLE dashboards DROP CONSTRAINT dashboards_workspace_id_fkey;
ALTER TABLE doc_permissions DROP CONSTRAINT doc_permissions_user_id_fkey;
ALTER TABLE doc_templates DROP CONSTRAINT doc_templates_created_by_fkey;
ALTER TABLE doc_templates DROP CONSTRAINT doc_templates_workspace_id_fkey;
ALTER TABLE doc_versions DROP CONSTRAINT doc_versions_created_by_fkey;
ALTER TABLE docs DROP CONSTRAINT docs_workspace_id_fkey;
ALTER TABLE docs DROP CONSTRAINT docs_created_by_fkey;
ALTER TABLE email_verification_tokens DROP CONSTRAINT email_verification_tokens_user_id_fkey;
ALTER TABLE favorites DROP CONSTRAINT favorites_user_id_fkey;
ALTER TABLE files DROP CONSTRAINT files_workspace_id_fkey;
ALTER TABLE files DROP CONSTRAINT files_uploaded_by_fkey;
ALTER TABLE folder_templates DROP CONSTRAINT folder_templates_created_by_fkey;
ALTER TABLE folder_templates DROP CONSTRAINT folder_templates_workspace_id_fkey;
ALTER TABLE folders DROP CONSTRAINT folders_created_by_fkey;
ALTER TABLE forms DROP CONSTRAINT forms_workspace_id_fkey;
ALTER TABLE forms DROP CONSTRAINT forms_created_by_fkey;
ALTER TABLE github_installations DROP CONSTRAINT github_installations_workspace_id_fkey;
ALTER TABLE github_installations DROP CONSTRAINT github_installations_installed_by_fkey;
ALTER TABLE github_pr_links DROP CONSTRAINT github_pr_links_workspace_id_fkey;
ALTER TABLE github_pr_links DROP CONSTRAINT github_pr_links_linked_by_fkey;
ALTER TABLE github_repo_subscriptions DROP CONSTRAINT github_repo_subscriptions_workspace_id_fkey;
ALTER TABLE gitlab_installations DROP CONSTRAINT gitlab_installations_installed_by_fkey;
ALTER TABLE gitlab_installations DROP CONSTRAINT gitlab_installations_workspace_id_fkey;
ALTER TABLE gitlab_mr_links DROP CONSTRAINT gitlab_mr_links_linked_by_fkey;
ALTER TABLE gitlab_mr_links DROP CONSTRAINT gitlab_mr_links_workspace_id_fkey;
ALTER TABLE goal_folders DROP CONSTRAINT goal_folders_created_by_fkey;
ALTER TABLE goal_folders DROP CONSTRAINT goal_folders_workspace_id_fkey;
ALTER TABLE goal_permissions DROP CONSTRAINT goal_permissions_user_id_fkey;
ALTER TABLE goal_permissions DROP CONSTRAINT goal_permissions_granted_by_fkey;
ALTER TABLE goals DROP CONSTRAINT goals_workspace_id_fkey;
ALTER TABLE goals DROP CONSTRAINT goals_owner_id_fkey;
ALTER TABLE guest_links DROP CONSTRAINT guest_links_created_by_fkey;
ALTER TABLE guest_links DROP CONSTRAINT guest_links_workspace_id_fkey;
ALTER TABLE list_templates DROP CONSTRAINT list_templates_created_by_fkey;
ALTER TABLE list_templates DROP CONSTRAINT list_templates_workspace_id_fkey;
ALTER TABLE lists DROP CONSTRAINT lists_created_by_fkey;
ALTER TABLE message_reactions DROP CONSTRAINT message_reactions_user_id_fkey;
ALTER TABLE notification_preferences DROP CONSTRAINT notification_preferences_user_id_fkey;
ALTER TABLE notification_preferences DROP CONSTRAINT notification_preferences_workspace_id_fkey;
ALTER TABLE notifications DROP CONSTRAINT notifications_user_id_fkey;
ALTER TABLE oauth_accounts DROP CONSTRAINT oauth_accounts_user_id_fkey;
ALTER TABLE password_reset_tokens DROP CONSTRAINT password_reset_tokens_user_id_fkey;
ALTER TABLE pinned_tasks DROP CONSTRAINT pinned_tasks_user_id_fkey;
ALTER TABLE push_subscriptions DROP CONSTRAINT push_subscriptions_user_id_fkey;
ALTER TABLE rate_limit_events DROP CONSTRAINT rate_limit_events_user_id_fkey;
ALTER TABLE rate_limit_events DROP CONSTRAINT rate_limit_events_workspace_id_fkey;
ALTER TABLE recently_viewed DROP CONSTRAINT recently_viewed_workspace_id_fkey;
ALTER TABLE recently_viewed DROP CONSTRAINT recently_viewed_user_id_fkey;
ALTER TABLE reminders DROP CONSTRAINT reminders_user_id_fkey;
ALTER TABLE saml_configs DROP CONSTRAINT saml_configs_workspace_id_fkey;
ALTER TABLE saml_configs DROP CONSTRAINT saml_configs_created_by_fkey;
ALTER TABLE saved_searches DROP CONSTRAINT saved_searches_user_id_fkey;
ALTER TABLE saved_searches DROP CONSTRAINT saved_searches_workspace_id_fkey;
ALTER TABLE sessions DROP CONSTRAINT sessions_user_id_fkey;
ALTER TABLE slack_channel_links DROP CONSTRAINT slack_channel_links_workspace_id_fkey;
ALTER TABLE slack_channel_links DROP CONSTRAINT slack_channel_links_created_by_fkey;
ALTER TABLE slack_installations DROP CONSTRAINT slack_installations_workspace_id_fkey;
ALTER TABLE slack_installations DROP CONSTRAINT slack_installations_installed_by_fkey;
ALTER TABLE space_templates DROP CONSTRAINT space_templates_workspace_id_fkey;
ALTER TABLE space_templates DROP CONSTRAINT space_templates_created_by_fkey;
ALTER TABLE spaces DROP CONSTRAINT spaces_workspace_id_fkey;
ALTER TABLE spaces DROP CONSTRAINT spaces_created_by_fkey;
ALTER TABLE sprints DROP CONSTRAINT sprints_created_by_fkey;
ALTER TABLE task_activity DROP CONSTRAINT task_activity_user_id_fkey;
ALTER TABLE task_assignees DROP CONSTRAINT task_assignees_assigned_by_fkey;
ALTER TABLE task_assignees DROP CONSTRAINT task_assignees_user_id_fkey;
ALTER TABLE task_forms DROP CONSTRAINT task_forms_created_by_fkey;
ALTER TABLE task_mirrors DROP CONSTRAINT task_mirrors_created_by_fkey;
ALTER TABLE task_permissions DROP CONSTRAINT task_permissions_user_id_fkey;
ALTER TABLE task_permissions DROP CONSTRAINT task_permissions_granted_by_fkey;
ALTER TABLE task_public_links DROP CONSTRAINT task_public_links_created_by_fkey;
ALTER TABLE task_relations DROP CONSTRAINT task_relations_created_by_fkey;
ALTER TABLE task_templates DROP CONSTRAINT task_templates_created_by_fkey;
ALTER TABLE task_templates DROP CONSTRAINT task_templates_workspace_id_fkey;
ALTER TABLE task_types DROP CONSTRAINT task_types_workspace_id_fkey;
ALTER TABLE task_watchers DROP CONSTRAINT task_watchers_user_id_fkey;
ALTER TABLE tasks DROP CONSTRAINT tasks_created_by_fkey;
ALTER TABLE tasks DROP CONSTRAINT tasks_assignee_id_fkey;
ALTER TABLE team_members DROP CONSTRAINT team_members_user_id_fkey;
ALTER TABLE teams DROP CONSTRAINT teams_created_by_fkey;
ALTER TABLE teams DROP CONSTRAINT teams_workspace_id_fkey;
ALTER TABLE time_entries DROP CONSTRAINT time_entries_user_id_fkey;
ALTER TABLE totp_secrets DROP CONSTRAINT totp_secrets_user_id_fkey;
ALTER TABLE user_preferences DROP CONSTRAINT user_preferences_user_id_fkey;
ALTER TABLE user_presence DROP CONSTRAINT user_presence_user_id_fkey;
ALTER TABLE user_sidebar_config DROP CONSTRAINT user_sidebar_config_user_id_fkey;
ALTER TABLE user_sidebar_config DROP CONSTRAINT user_sidebar_config_workspace_id_fkey;
ALTER TABLE view_user_state DROP CONSTRAINT view_user_state_user_id_fkey;
ALTER TABLE views DROP CONSTRAINT views_created_by_fkey;
ALTER TABLE views DROP CONSTRAINT views_workspace_id_fkey;
ALTER TABLE webhook_subscriptions DROP CONSTRAINT webhook_subscriptions_created_by_fkey;
ALTER TABLE webhook_subscriptions DROP CONSTRAINT webhook_subscriptions_workspace_id_fkey;
ALTER TABLE workspace_clickapps DROP CONSTRAINT workspace_clickapps_workspace_id_fkey;
ALTER TABLE workspace_invites DROP CONSTRAINT workspace_invites_invited_by_fkey;
ALTER TABLE workspace_invites DROP CONSTRAINT workspace_invites_workspace_id_fkey;
ALTER TABLE workspace_members DROP CONSTRAINT workspace_members_user_id_fkey;
ALTER TABLE workspace_members DROP CONSTRAINT workspace_members_workspace_id_fkey;
ALTER TABLE workspaces DROP CONSTRAINT workspaces_owner_id_fkey;

-- ── Step 2: Change PK columns to TEXT ────────────────────────────────────────

ALTER TABLE users ALTER COLUMN id TYPE TEXT;
ALTER TABLE users ALTER COLUMN id DROP DEFAULT;

ALTER TABLE workspaces ALTER COLUMN id TYPE TEXT;
ALTER TABLE workspaces ALTER COLUMN id DROP DEFAULT;

-- ── Step 3: Change all FK columns to TEXT ────────────────────────────────────

ALTER TABLE api_keys ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE api_keys ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE audit_logs ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE audit_logs ALTER COLUMN actor_id TYPE TEXT;
ALTER TABLE automation_runs ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE automations ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE automations ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE channel_members ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE channels ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE channels ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE chat_mentions ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE chat_messages ALTER COLUMN sender_id TYPE TEXT;
ALTER TABLE checklist_items ALTER COLUMN assignee_id TYPE TEXT;
ALTER TABLE comment_assignments ALTER COLUMN assigned_by TYPE TEXT;
ALTER TABLE comment_assignments ALTER COLUMN assignee_id TYPE TEXT;
ALTER TABLE comment_reactions ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE comments ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE custom_fields ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE dashboards ALTER COLUMN owner_id TYPE TEXT;
ALTER TABLE dashboards ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE doc_permissions ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE doc_templates ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE doc_templates ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE doc_versions ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE docs ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE docs ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE email_verification_tokens ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE favorites ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE files ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE files ALTER COLUMN uploaded_by TYPE TEXT;
ALTER TABLE folder_templates ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE folder_templates ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE folders ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE forms ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE forms ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE github_installations ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE github_installations ALTER COLUMN installed_by TYPE TEXT;
ALTER TABLE github_pr_links ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE github_pr_links ALTER COLUMN linked_by TYPE TEXT;
ALTER TABLE github_repo_subscriptions ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE gitlab_installations ALTER COLUMN installed_by TYPE TEXT;
ALTER TABLE gitlab_installations ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE gitlab_mr_links ALTER COLUMN linked_by TYPE TEXT;
ALTER TABLE gitlab_mr_links ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE goal_folders ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE goal_folders ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE goal_permissions ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE goal_permissions ALTER COLUMN granted_by TYPE TEXT;
ALTER TABLE goals ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE goals ALTER COLUMN owner_id TYPE TEXT;
ALTER TABLE guest_links ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE guest_links ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE list_templates ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE list_templates ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE lists ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE message_reactions ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE notification_preferences ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE notification_preferences ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE notifications ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE oauth_accounts ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE password_reset_tokens ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE pinned_tasks ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE push_subscriptions ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE rate_limit_events ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE rate_limit_events ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE recently_viewed ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE recently_viewed ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE reminders ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE saml_configs ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE saml_configs ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE saved_searches ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE saved_searches ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE sessions ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE slack_channel_links ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE slack_channel_links ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE slack_installations ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE slack_installations ALTER COLUMN installed_by TYPE TEXT;
ALTER TABLE space_templates ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE space_templates ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE spaces ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE spaces ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE sprints ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE task_activity ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE task_assignees ALTER COLUMN assigned_by TYPE TEXT;
ALTER TABLE task_assignees ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE task_forms ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE task_mirrors ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE task_permissions ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE task_permissions ALTER COLUMN granted_by TYPE TEXT;
ALTER TABLE task_public_links ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE task_relations ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE task_templates ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE task_templates ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE task_types ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE task_watchers ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE tasks ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE tasks ALTER COLUMN assignee_id TYPE TEXT;
ALTER TABLE team_members ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE teams ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE teams ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE time_entries ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE totp_secrets ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE user_preferences ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE user_presence ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE user_sidebar_config ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE user_sidebar_config ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE view_user_state ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE views ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE views ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE webhook_subscriptions ALTER COLUMN created_by TYPE TEXT;
ALTER TABLE webhook_subscriptions ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE workspace_clickapps ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE workspace_invites ALTER COLUMN invited_by TYPE TEXT;
ALTER TABLE workspace_invites ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE workspace_members ALTER COLUMN user_id TYPE TEXT;
ALTER TABLE workspace_members ALTER COLUMN workspace_id TYPE TEXT;
ALTER TABLE workspaces ALTER COLUMN owner_id TYPE TEXT;

-- ── Step 4: Re-add FK constraints ────────────────────────────────────────────

ALTER TABLE workspaces ADD CONSTRAINT workspaces_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users(id);
ALTER TABLE workspace_members ADD CONSTRAINT workspace_members_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE;
ALTER TABLE workspace_members ADD CONSTRAINT workspace_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE sessions ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE spaces ADD CONSTRAINT spaces_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE;
ALTER TABLE spaces ADD CONSTRAINT spaces_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE folders ADD CONSTRAINT folders_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE lists ADD CONSTRAINT lists_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE tasks ADD CONSTRAINT tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE tasks ADD CONSTRAINT tasks_assignee_id_fkey FOREIGN KEY (assignee_id) REFERENCES users(id);
ALTER TABLE task_assignees ADD CONSTRAINT task_assignees_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE task_assignees ADD CONSTRAINT task_assignees_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES users(id);
ALTER TABLE task_watchers ADD CONSTRAINT task_watchers_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE task_activity ADD CONSTRAINT task_activity_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE task_relations ADD CONSTRAINT task_relations_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE task_permissions ADD CONSTRAINT task_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE task_permissions ADD CONSTRAINT task_permissions_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES users(id);
ALTER TABLE task_mirrors ADD CONSTRAINT task_mirrors_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE task_public_links ADD CONSTRAINT task_public_links_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE task_forms ADD CONSTRAINT task_forms_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE task_templates ADD CONSTRAINT task_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE task_templates ADD CONSTRAINT task_templates_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE task_types ADD CONSTRAINT task_types_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE comments ADD CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE comment_reactions ADD CONSTRAINT comment_reactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE comment_assignments ADD CONSTRAINT comment_assignments_assignee_id_fkey FOREIGN KEY (assignee_id) REFERENCES users(id);
ALTER TABLE comment_assignments ADD CONSTRAINT comment_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES users(id);
ALTER TABLE checklist_items ADD CONSTRAINT checklist_items_assignee_id_fkey FOREIGN KEY (assignee_id) REFERENCES users(id);
ALTER TABLE time_entries ADD CONSTRAINT time_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE reminders ADD CONSTRAINT reminders_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE pinned_tasks ADD CONSTRAINT pinned_tasks_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE custom_fields ADD CONSTRAINT custom_fields_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE docs ADD CONSTRAINT docs_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE;
ALTER TABLE docs ADD CONSTRAINT docs_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE doc_versions ADD CONSTRAINT doc_versions_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE doc_permissions ADD CONSTRAINT doc_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE doc_templates ADD CONSTRAINT doc_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE doc_templates ADD CONSTRAINT doc_templates_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE goals ADD CONSTRAINT goals_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE;
ALTER TABLE goals ADD CONSTRAINT goals_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users(id);
ALTER TABLE goal_folders ADD CONSTRAINT goal_folders_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE goal_folders ADD CONSTRAINT goal_folders_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE goal_permissions ADD CONSTRAINT goal_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE goal_permissions ADD CONSTRAINT goal_permissions_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES users(id);
ALTER TABLE views ADD CONSTRAINT views_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE views ADD CONSTRAINT views_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE view_user_state ADD CONSTRAINT view_user_state_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE dashboards ADD CONSTRAINT dashboards_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users(id);
ALTER TABLE dashboards ADD CONSTRAINT dashboards_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE automations ADD CONSTRAINT automations_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE automations ADD CONSTRAINT automations_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE automation_runs ADD CONSTRAINT automation_runs_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE webhook_subscriptions ADD CONSTRAINT webhook_subscriptions_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE webhook_subscriptions ADD CONSTRAINT webhook_subscriptions_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE notification_preferences ADD CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE notification_preferences ADD CONSTRAINT notification_preferences_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE push_subscriptions ADD CONSTRAINT push_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE files ADD CONSTRAINT files_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE files ADD CONSTRAINT files_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES users(id);
ALTER TABLE favorites ADD CONSTRAINT favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE recently_viewed ADD CONSTRAINT recently_viewed_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE recently_viewed ADD CONSTRAINT recently_viewed_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE user_preferences ADD CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE user_presence ADD CONSTRAINT user_presence_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE user_sidebar_config ADD CONSTRAINT user_sidebar_config_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE user_sidebar_config ADD CONSTRAINT user_sidebar_config_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE saved_searches ADD CONSTRAINT saved_searches_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE saved_searches ADD CONSTRAINT saved_searches_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE teams ADD CONSTRAINT teams_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE teams ADD CONSTRAINT teams_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE team_members ADD CONSTRAINT team_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE forms ADD CONSTRAINT forms_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE forms ADD CONSTRAINT forms_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES users(id);
ALTER TABLE api_keys ADD CONSTRAINT api_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE api_keys ADD CONSTRAINT api_keys_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE sprints ADD CONSTRAINT sprints_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE channels ADD CONSTRAINT channels_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE channels ADD CONSTRAINT channels_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE channel_members ADD CONSTRAINT channel_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE chat_messages ADD CONSTRAINT chat_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES users(id);
ALTER TABLE chat_mentions ADD CONSTRAINT chat_mentions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE message_reactions ADD CONSTRAINT message_reactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE totp_secrets ADD CONSTRAINT totp_secrets_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE oauth_accounts ADD CONSTRAINT oauth_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE email_verification_tokens ADD CONSTRAINT email_verification_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE password_reset_tokens ADD CONSTRAINT password_reset_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE rate_limit_events ADD CONSTRAINT rate_limit_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE rate_limit_events ADD CONSTRAINT rate_limit_events_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE guest_links ADD CONSTRAINT guest_links_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE guest_links ADD CONSTRAINT guest_links_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE workspace_invites ADD CONSTRAINT workspace_invites_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES users(id);
ALTER TABLE workspace_invites ADD CONSTRAINT workspace_invites_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE workspace_clickapps ADD CONSTRAINT workspace_clickapps_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE saml_configs ADD CONSTRAINT saml_configs_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE saml_configs ADD CONSTRAINT saml_configs_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE github_installations ADD CONSTRAINT github_installations_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE github_installations ADD CONSTRAINT github_installations_installed_by_fkey FOREIGN KEY (installed_by) REFERENCES users(id);
ALTER TABLE github_repo_subscriptions ADD CONSTRAINT github_repo_subscriptions_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE github_pr_links ADD CONSTRAINT github_pr_links_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE github_pr_links ADD CONSTRAINT github_pr_links_linked_by_fkey FOREIGN KEY (linked_by) REFERENCES users(id);
ALTER TABLE gitlab_installations ADD CONSTRAINT gitlab_installations_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE gitlab_installations ADD CONSTRAINT gitlab_installations_installed_by_fkey FOREIGN KEY (installed_by) REFERENCES users(id);
ALTER TABLE gitlab_mr_links ADD CONSTRAINT gitlab_mr_links_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE gitlab_mr_links ADD CONSTRAINT gitlab_mr_links_linked_by_fkey FOREIGN KEY (linked_by) REFERENCES users(id);
ALTER TABLE slack_installations ADD CONSTRAINT slack_installations_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE slack_installations ADD CONSTRAINT slack_installations_installed_by_fkey FOREIGN KEY (installed_by) REFERENCES users(id);
ALTER TABLE slack_channel_links ADD CONSTRAINT slack_channel_links_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE slack_channel_links ADD CONSTRAINT slack_channel_links_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE space_templates ADD CONSTRAINT space_templates_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE space_templates ADD CONSTRAINT space_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE list_templates ADD CONSTRAINT list_templates_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE list_templates ADD CONSTRAINT list_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE folder_templates ADD CONSTRAINT folder_templates_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id);
ALTER TABLE folder_templates ADD CONSTRAINT folder_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);

COMMIT;
